apiVersion: v1
data:
  public.pem: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2WmZlYTdkL2ZZYXhWY2FWaTgrdApQVnZRTWNWemk2SUVKOVFWb2VxSEtZcThYck9VaXhNNnRYQzYxVnlTMzVFcVlWRzZsVW9uQzJCYksweTZabUNsClFIeWNmendkckM2S09hSHNMVTBHMjFoQXU5WVRzeWpmSnFRSHFrTkZnVE5CMmpBSUxRK25Tak9TZVhKcnpHT3EKL1F2Wk5abDZ5a2d6ZVd6VlpqTXRtSHNUTGVZRERFOEh4WXI3NDhyYVlTcTAvUktNSk1sZ1ZqZ1EyL3NVbzQxbgpzWDZlUXRVVmxRZ1FDYUxXb2xOajFheTMrdlhabE9iQ2ZadkJwRVZ0S1hCL2h5TWxIczI2QjBEWDRHNWdWVjk1CnE1bVFtbWpZU1VBdCt6QWhpaTQydlJqTVhuc3VyVnNGQndJbmgrTzlVbkFjTWRINHRTMlZ0K3BJWC9PZGFFZSsKdFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: jwt-public-key
  namespace: recruitment
