package com.example.application_service.service;
import com.example.application_service.client.InternalServiceClient;import com.example.application_service.dto.ApplicationDtos;import com.example.application_service.entity.*;import com.example.application_service.exception.ApiException;import com.example.application_service.repository.*;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.annotation.Transactional;import org.springframework.transaction.support.TransactionTemplate;import java.util.*;
@Service public class ApplicationService{private final JobApplicationRepository applications;private final ApplicationStatusHistoryRepository histories;private final InternalServiceClient internal;private final ApplicationRules rules;private final OutboxService outbox;private final TransactionTemplate transactions;public ApplicationService(JobApplicationRepository a,ApplicationStatusHistoryRepository h,InternalServiceClient i,ApplicationRules r,OutboxService outbox,PlatformTransactionManager tm){applications=a;histories=h;internal=i;rules=r;this.outbox=outbox;transactions=new TransactionTemplate(tm);}
 public ApplicationDtos.View apply(ApplicationDtos.Apply request,UUID candidate,String email,String trace){if(applications.existsByCandidateIdAndJobId(candidate,request.jobId()))throw duplicate();var job=internal.job(request.jobId(),trace);if(job==null||!job.acceptingApplications)throw new ApiException(HttpStatus.CONFLICT,"JOB_APPLICATION_CLOSED","Job is not accepting applications");var cv=internal.cv(request.cvId(),candidate,trace);if(cv==null||!cv.valid||!candidate.equals(cv.candidateId))throw new ApiException(HttpStatus.NOT_FOUND,"CV_NOT_FOUND","CV was not found or does not belong to the candidate");try{return transactions.execute(s->{JobApplication entity=applications.saveAndFlush(new JobApplication(job.jobId,candidate,job.createdBy,job.companyId,cv.cvId,cv.objectKey,cv.fileName,job.title,email,request.coverLetter()));histories.save(new ApplicationStatusHistory(entity.getId(),null,ApplicationStatus.APPLIED,candidate,"Application submitted"));outbox.submitted(entity,trace);return view(entity);});}catch(DataIntegrityViolationException e){throw duplicate();}}
 @Transactional(readOnly=true)public ApplicationDtos.PageData<ApplicationDtos.View> candidateList(UUID candidate,int page,int size,String sort){return page(applications.findByCandidateId(candidate,pageable(page,size,sort)));}
 public ApplicationDtos.PageData<ApplicationDtos.View> employerList(UUID jobId,UUID employer,String trace,int page,int size,String sort){var job=internal.job(jobId,trace);if(job==null)throw new ApiException(HttpStatus.NOT_FOUND,"JOB_NOT_FOUND","Job was not found");internal.requireCompany(job.companyId,employer,trace);return loadJob(jobId,page,size,sort);}
 @Transactional(readOnly=true)protected ApplicationDtos.PageData<ApplicationDtos.View> loadJob(UUID jobId,int page,int size,String sort){return page(applications.findByJobId(jobId,pageable(page,size,sort)));}
 public ApplicationDtos.Detail detail(UUID id,UUID actor,String role,String trace){JobApplication app=find(id);if("CANDIDATE".equals(role)){if(!app.getCandidateId().equals(actor))throw forbidden();}else if("EMPLOYER".equals(role)){internal.requireCompany(app.getCompanyId(),actor,trace);}else throw forbidden();return loadDetail(id);}
 @Transactional(readOnly=true)protected ApplicationDtos.Detail loadDetail(UUID id){JobApplication app=find(id);return new ApplicationDtos.Detail(view(app),histories.findByApplicationIdOrderByCreatedAtAsc(id).stream().map(this::history).toList());}
 public ApplicationDtos.Detail changeStatus(UUID id,ApplicationDtos.StatusChange request,UUID employer,String trace){JobApplication snapshot=find(id);internal.requireCompany(snapshot.getCompanyId(),employer,trace);return transactions.execute(s->{JobApplication app=find(id);if(app.getVersion()!=request.version())throw new ApiException(HttpStatus.CONFLICT,"OPTIMISTIC_LOCK_CONFLICT","Application was updated by another request");ApplicationStatus from=app.getStatus();rules.transition(from,request.newStatus());app.transition(request.newStatus());applications.saveAndFlush(app);histories.save(new ApplicationStatusHistory(app.getId(),from,request.newStatus(),employer,request.note()));outbox.statusChanged(app,from,trace);return loadDetail(id);});}
 private JobApplication find(UUID id){return applications.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"APPLICATION_NOT_FOUND","Application was not found"));}private ApiException duplicate(){return new ApiException(HttpStatus.CONFLICT,"APPLICATION_ALREADY_EXISTS","You have already applied for this job");}private ApiException forbidden(){return new ApiException(HttpStatus.FORBIDDEN,"RESOURCE_FORBIDDEN","You cannot access this application");}
 private Pageable pageable(int page,int size,String value){if(page<0||size<1||size>100)throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Invalid pagination");Sort sort=switch(value==null?"newest":value){case "newest","createdAt,desc"->Sort.by(Sort.Direction.DESC,"createdAt");case "oldest","createdAt,asc"->Sort.by(Sort.Direction.ASC,"createdAt");default->throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Unsupported sort value");};return PageRequest.of(page,size,sort);}private ApplicationDtos.PageData<ApplicationDtos.View> page(Page<JobApplication> p){return new ApplicationDtos.PageData<>(p.stream().map(this::view).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages(),p.isFirst(),p.isLast());}
 private ApplicationDtos.View view(JobApplication a){return new ApplicationDtos.View(a.getId(),a.getJobId(),a.getCandidateId(),a.getCompanyId(),a.getCvId(),a.getCvFileNameSnapshot(),a.getJobTitleSnapshot(),a.getCandidateIdentitySnapshot(),a.getCoverLetter(),a.getStatus(),a.getCreatedAt(),a.getUpdatedAt(),a.getVersion());}private ApplicationDtos.HistoryView history(ApplicationStatusHistory h){return new ApplicationDtos.HistoryView(h.getId(),h.getFromStatus(),h.getToStatus(),h.getChangedBy(),h.getNote(),h.getCreatedAt());}}
