import{cloneElement,isValidElement,useId,type PropsWithChildren,type ReactElement,type ReactNode}from'react';import{AlertCircle,BriefcaseBusiness,ChevronRight,LoaderCircle}from'lucide-react';import{Link}from'react-router-dom';
export function Page({title,eyebrow,description,actions,breadcrumbs,children}:PropsWithChildren<{title:string;eyebrow?:string;description?:string;actions?:ReactNode;breadcrumbs?:Array<{label:string;to?:string}>}>){return <main className="page" id="main-content">{breadcrumbs&&<nav className="breadcrumb" aria-label="Điều hướng phân cấp"><Link to="/">Trang chủ</Link>{breadcrumbs.map((item,index)=><span key={`${item.label}-${index}`}><ChevronRight/>{item.to?<Link to={item.to}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}</span>)}</nav>}<header className="page-head"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</header>{children}</main>}
export function Loading({label='Đang tải dữ liệu…'}:{label?:string}){return <div className="state" role="status"><LoaderCircle className="spin"/><p>{label}</p></div>}
export function Empty({title='Chưa có dữ liệu',text='Nội dung sẽ xuất hiện tại đây khi có dữ liệu.',action}:{title?:string;text?:string;action?:ReactNode}){return <div className="state state-empty"><span className="state-icon"><BriefcaseBusiness/></span><h2>{title}</h2><p>{text}</p>{action}</div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="state error" role="alert"><AlertCircle/><h2>Không thể tải dữ liệu</h2><p>{message}</p>{retry&&<button onClick={retry}>Thử lại</button>}</div>}
export function Field({label,error,children,hint}:{label:string;error?:string;children:ReactNode;hint?:string}){const id=useId();const helpId=`${id}-help`;const control=isValidElement(children)?cloneElement(children as ReactElement<{id?:string;'aria-describedby'?:string}>,{id,'aria-describedby':hint||error?helpId:undefined}):children;return <div className="field"><label htmlFor={id}>{label}</label>{control}{(hint||error)&&<small id={helpId} className={error?'field-error':undefined} role={error?'alert':undefined}>{error||hint}</small>}</div>}
const statusLabels:Record<string,string>={APPLIED:'Đã ứng tuyển',SCREENING:'Đang sàng lọc',INTERVIEW:'Phỏng vấn',OFFER:'Đã gửi đề nghị',HIRED:'Đã tuyển',REJECTED:'Không phù hợp',DRAFT:'Bản nháp',PUBLISHED:'Đang tuyển',HIDDEN:'Đã ẩn',CLOSED:'Đã đóng',FULL_TIME:'Toàn thời gian',PART_TIME:'Bán thời gian',CONTRACT:'Hợp đồng',INTERNSHIP:'Thực tập',FREELANCE:'Tự do',DEFAULT:'Mặc định'};
export function Status({value}:{value:string}){return <span className={`status status-${value.toLowerCase()}`} title={value}><i aria-hidden="true"/><span>{statusLabels[value]??value.replaceAll('_',' ')}</span><span className="sr-only">{value}</span></span>}
export function Pager({page,total,onPage}:{page:number;total:number;onPage:(p:number)=>void}){if(total<=1)return null;return <nav className="pager" aria-label="Phân trang"><button disabled={page===0} onClick={()=>onPage(page-1)}>Trước</button><span>Trang {page+1} / {total}</span><button disabled={page+1>=total} onClick={()=>onPage(page+1)}>Sau</button></nav>}
