spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
server:
  port: ${SERVER_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{correlationId:-}]"
security:
  jwt:
    issuer: ${JWT_ISSUER:recruitment-auth-service}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800s}
    private-key: ${JWT_PRIVATE_KEY:classpath:keys/dev-private.pem}
    public-key: ${JWT_PUBLIC_KEY:classpath:keys/dev-public.pem}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:604800s}
