package com.example.user_service.service;
import com.example.user_service.dto.CompanyDtos; import com.example.user_service.entity.*; import com.example.user_service.exception.ApiException; import com.example.user_service.repository.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.UUID;
@Service public class CompanyService {private final CompanyRepository companies;private final CompanyMemberRepository members;public CompanyService(CompanyRepository c,CompanyMemberRepository m){companies=c;members=m;}
 @Transactional public CompanyDtos.View create(UUID user,CompanyDtos.Upsert x){Company c=companies.save(new Company(x.name(),x.description(),x.address()));members.save(new CompanyMember(c.getId(),user,MemberRole.OWNER));return view(c);}
 @Transactional(readOnly=true) public CompanyDtos.View get(UUID id){return view(find(id));}
 @Transactional public CompanyDtos.View update(UUID id,UUID user,CompanyDtos.Upsert x){CompanyMember m=membership(id,user);if(m.getMemberRole()!=MemberRole.OWNER)throw forbidden();Company c=find(id);c.update(x.name(),x.description(),x.address());return view(c);}
 @Transactional public void addMember(UUID id,UUID owner,UUID user,MemberRole requested){if(membership(id,owner).getMemberRole()!=MemberRole.OWNER)throw forbidden();find(id);if(members.existsByCompanyIdAndUserId(id,user))throw new ApiException(HttpStatus.CONFLICT,"COMPANY_MEMBER_ALREADY_EXISTS","User is already a company member");if(requested==MemberRole.OWNER)throw new ApiException(HttpStatus.FORBIDDEN,"OWNER_ASSIGNMENT_NOT_ALLOWED","Owners cannot be assigned through this endpoint");members.save(new CompanyMember(id,user,MemberRole.RECRUITER));}
 @Transactional(readOnly=true) public CompanyDtos.Authorization authorization(UUID id,UUID user){return members.findByCompanyIdAndUserId(id,user).map(m->new CompanyDtos.Authorization(true,m.getMemberRole())).orElse(new CompanyDtos.Authorization(false,null));}
 private Company find(UUID id){return companies.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"COMPANY_NOT_FOUND","Company was not found"));} private CompanyMember membership(UUID c,UUID u){return members.findByCompanyIdAndUserId(c,u).orElseThrow(this::forbidden);} private ApiException forbidden(){return new ApiException(HttpStatus.FORBIDDEN,"RESOURCE_FORBIDDEN","You cannot manage this company");} private CompanyDtos.View view(Company c){return new CompanyDtos.View(c.getId(),c.getName(),c.getDescription(),c.getAddress(),c.getStatus(),c.getCreatedAt(),c.getUpdatedAt(),c.getVersion());}}
