package com.example.user_service.service;
import com.example.user_service.dto.CvDtos; import com.example.user_service.entity.Cv; import com.example.user_service.exception.ApiException; import com.example.user_service.repository.CvRepository; import com.example.user_service.storage.ObjectStorage; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.util.*;
@Service public class CvService {private static final byte[] PDF={'%','P','D','F','-'};private final CvRepository repo;private final ObjectStorage storage;private final long max;public CvService(CvRepository r,ObjectStorage s,@Value("${user-service.cv.max-size-bytes}")long max){repo=r;storage=s;this.max=max;}
 @Transactional public CvDtos.View upload(UUID candidate,MultipartFile file,boolean defaultCv){validate(file);String key="cvs/"+candidate+"/"+UUID.randomUUID()+".pdf";try(InputStream in=file.getInputStream()){storage.put(key,in,file.getSize(),MediaType.APPLICATION_PDF_VALUE);}catch(IOException e){throw unavailable();}try{return view(repo.saveAndFlush(new Cv(candidate,safeName(file.getOriginalFilename()),key,MediaType.APPLICATION_PDF_VALUE,file.getSize(),defaultCv)));}catch(RuntimeException e){try{storage.delete(key);}catch(RuntimeException ignored){}throw e;}}
 @Transactional(readOnly=true) public List<CvDtos.View> list(UUID candidate){return repo.findAllByCandidateIdOrderByCreatedAtDesc(candidate).stream().map(this::view).toList();}
 @Transactional public void delete(UUID candidate,UUID id){Cv cv=repo.findByIdAndCandidateId(id,candidate).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CV_NOT_FOUND","CV was not found"));storage.delete(cv.getObjectKey());repo.delete(cv);}
 @Transactional(readOnly=true) public CvDtos.Validation validateOwnership(UUID id,UUID candidate){return repo.findByIdAndCandidateId(id,candidate).map(c->new CvDtos.Validation(c.getId(),c.getCandidateId(),c.getFileName(),c.getObjectKey(),c.getContentType(),c.getSizeBytes(),true)).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CV_NOT_FOUND","CV does not belong to candidate"));}
 private void validate(MultipartFile f){String n=f.getOriginalFilename();if(f.isEmpty())throw unsupported();if(f.getSize()>max)throw new ApiException(HttpStatus.PAYLOAD_TOO_LARGE,"FILE_TOO_LARGE","CV exceeds the configured size limit");if(n==null||!n.toLowerCase(Locale.ROOT).endsWith(".pdf"))throw unsupported();if(!MediaType.APPLICATION_PDF_VALUE.equalsIgnoreCase(f.getContentType()))throw unsupported();try(InputStream in=f.getInputStream()){if(!Arrays.equals(PDF,in.readNBytes(PDF.length)))throw unsupported();}catch(IOException e){throw unsupported();}}
 private String safeName(String n){String base=n==null?"cv.pdf":n.replace('\\','/');base=base.substring(base.lastIndexOf('/')+1);return base.length()>255?base.substring(base.length()-255):base;}
 private CvDtos.View view(Cv c){return new CvDtos.View(c.getId(),c.getFileName(),c.getContentType(),c.getSizeBytes(),c.isDefaultCv(),c.getCreatedAt());} private ApiException unsupported(){return new ApiException(HttpStatus.UNSUPPORTED_MEDIA_TYPE,"UNSUPPORTED_FILE_TYPE","Only valid PDF files are accepted");}private ApiException unavailable(){return new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"DEPENDENCY_UNAVAILABLE","Object storage is unavailable");}}
