import{api,data}from'./client';import type{ApiResponse,Application,ApplicationDetail,ApplicationStatus,Company,Cv,EmploymentType,Job,JobStatus,PageData,Profile,Role,Tokens,UserRegistration}from'../types/api';
export const authApi={register:(email:string,password:string,role:Role)=>data<UserRegistration>(api.post('/api/v1/auth/register',{email,password,role})),login:(email:string,password:string)=>data<Tokens>(api.post('/api/v1/auth/login',{email,password}))};
export const profileApi={get:()=>data<Profile>(api.get('/api/v1/candidates/me')),update:(body:Partial<Pick<Profile,'fullName'|'phone'|'headline'|'summary'|'locationId'>>)=>data<Profile>(api.put('/api/v1/candidates/me',body)),cvs:()=>data<Cv[]>(api.get('/api/v1/candidates/me/cvs')),upload:async(file:File,isDefault:boolean)=>{const form=new FormData();form.append('file',file);return data<Cv>(api.post(`/api/v1/candidates/me/cvs?isDefault=${isDefault}`,form))},deleteCv:(id:string)=>api.delete(`/api/v1/candidates/me/cvs/${id}`)};
export const companyApi={create:(body:{name:string;description?:string;address?:string})=>data<Company>(api.post('/api/v1/companies',body)),get:(id:string)=>data<Company>(api.get(`/api/v1/companies/${id}`)),update:(id:string,body:{name:string;description?:string;address?:string})=>data<Company>(api.put(`/api/v1/companies/${id}`,body)),addMember:(id:string,userId:string)=>data<null>(api.post(`/api/v1/companies/${id}/members`,{userId,role:'RECRUITER'}))};
export interface JobFilters{keyword?:string;locationId?:string;categoryId?:string;salaryMin?:number;employmentType?:EmploymentType;page?:number;size?:number;sort?:string}
export interface JobWrite{companyId:string;title:string;description:string;requirements:string;locationId:string;categoryId:string;employmentType:EmploymentType;salaryMin:number|null;salaryMax:number|null;salaryCurrency:string;salaryNegotiable:boolean;applicationDeadline:string;version:number|null}
const employmentTypes:EmploymentType[]=['FULL_TIME','PART_TIME','CONTRACT','INTERNSHIP','FREELANCE'];
const validJobFilters=(filters:JobFilters):JobFilters=>({...filters,employmentType:employmentTypes.includes(filters.employmentType as EmploymentType)?filters.employmentType:undefined,salaryMin:filters.salaryMin!=null&&filters.salaryMin>=0?filters.salaryMin:undefined});
export const jobApi={search:(filters:JobFilters)=>data<PageData<Job>>(api.get('/api/v1/jobs',{params:validJobFilters(filters)})),detail:(id:string)=>data<Job>(api.get(`/api/v1/jobs/${id}`)),employer:(companyId:string,status?:JobStatus,page=0)=>data<PageData<Job>>(api.get('/api/v1/employer/jobs',{params:{companyId,status,page,size:20}})),create:(body:JobWrite)=>data<Job>(api.post('/api/v1/jobs',body)),update:(id:string,body:JobWrite)=>data<Job>(api.put(`/api/v1/jobs/${id}`,body)),status:(id:string,status:JobStatus,version:number)=>data<Job>(api.patch(`/api/v1/jobs/${id}/status`,{status,version}))};
export const applicationApi={apply:(jobId:string,cvId:string,coverLetter?:string)=>data<Application>(api.post('/api/v1/applications',{jobId,cvId,coverLetter})),mine:(page=0)=>data<PageData<Application>>(api.get('/api/v1/applications/me',{params:{page,size:20,sort:'newest'}})),detail:(id:string)=>data<ApplicationDetail>(api.get(`/api/v1/applications/${id}`)),forJob:(jobId:string,page=0)=>data<PageData<Application>>(api.get(`/api/v1/employer/jobs/${jobId}/applications`,{params:{page,size:20,sort:'newest'}})),status:(id:string,newStatus:ApplicationStatus,note:string|undefined,version:number)=>data<ApplicationDetail>(api.patch(`/api/v1/applications/${id}/status`,{newStatus,note,version}))};
export function readEnvelope<T>(response:ApiResponse<T>){return response.data}
