apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  variant: Calico
  calicoNetwork:
    linuxDataplane: Iptables
    bgp: Disabled
    nodeAddressAutodetectionV4:
      interface: ens33
    ipPools:
      - name: kltn-ipv4-pool
        blockSize: 26
        cidr: 10.244.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
