package com.example.user_service;

import com.example.user_service.storage.ObjectStorage; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.*; import org.springframework.boot.test.context.TestConfiguration; import org.springframework.context.annotation.*; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.*; import org.springframework.test.web.servlet.MockMvc; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.*; import java.io.*; import java.util.*; import java.util.concurrent.ConcurrentHashMap; import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@Testcontainers @SpringBootTest(properties={"user-service.internal-token=test-internal-secret","user-service.cv.max-size-bytes=32","user-service.minio.enabled=false"}) @AutoConfigureMockMvc @Import(UserServiceApplicationTests.StorageConfig.class)
class UserServiceApplicationTests {
 @Container static PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:17-alpine");
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);}
 @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc; @Autowired MemoryStorage storage;
 @BeforeEach void clean(){jdbc.update("delete from cvs");jdbc.update("delete from company_members");jdbc.update("delete from companies");jdbc.update("delete from candidate_profiles");storage.objects.clear();}
 @Test void migrationAndRepositoriesUseExpectedSchema(){Integer n=jdbc.queryForObject("select count(*) from information_schema.tables where table_schema='public' and table_name in ('candidate_profiles','companies','company_members','cvs')",Integer.class);assertThat(n).isEqualTo(4);}
 @Test void candidateCanCreateReadAndUpdateOwnProfile()throws Exception{UUID u=UUID.randomUUID();mvc.perform(put("/api/v1/candidates/me").headers(identity(u,"CANDIDATE")).contentType(MediaType.APPLICATION_JSON).content("{\"fullName\":\"Ada\",\"headline\":\"Java\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.userId").value(u.toString())).andExpect(jsonPath("$.data.fullName").value("Ada"));mvc.perform(get("/api/v1/candidates/me").headers(identity(u,"CANDIDATE"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.headline").value("Java"));}
 @Test void employerCannotUseCandidateEndpoint()throws Exception{mvc.perform(get("/api/v1/candidates/me").headers(identity(UUID.randomUUID(),"EMPLOYER"))).andExpect(status().isForbidden());}
 @Test void profileRequestCannotChooseAnotherUser()throws Exception{UUID a=UUID.randomUUID(),b=UUID.randomUUID();mvc.perform(put("/api/v1/candidates/me").headers(identity(a,"CANDIDATE")).contentType(MediaType.APPLICATION_JSON).content("{\"fullName\":\"A\",\"userId\":\""+b+"\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.userId").value(a.toString()));}
 @Test void employerCreatesCompanyAndBecomesOwner()throws Exception{String id=createCompany(UUID.randomUUID());assertThat(jdbc.queryForObject("select member_role from company_members where company_id=?",String.class,UUID.fromString(id))).isEqualTo("OWNER");}
 @Test void outsiderCannotUpdateCompany()throws Exception{String id=createCompany(UUID.randomUUID());mvc.perform(put("/api/v1/companies/{id}",id).headers(identity(UUID.randomUUID(),"EMPLOYER")).contentType(MediaType.APPLICATION_JSON).content(companyJson("No"))).andExpect(status().isForbidden());}
 @Test void recruiterCannotUpdateCompany()throws Exception{UUID owner=UUID.randomUUID(),recruiter=UUID.randomUUID();String id=createCompany(owner);addMember(id,owner,recruiter).andExpect(status().isCreated());mvc.perform(put("/api/v1/companies/{id}",id).headers(identity(recruiter,"EMPLOYER")).contentType(MediaType.APPLICATION_JSON).content(companyJson("No"))).andExpect(status().isForbidden());}
 @Test void duplicateMemberConflictsAndOwnerCannotBeGranted()throws Exception{UUID owner=UUID.randomUUID(),member=UUID.randomUUID();String id=createCompany(owner);addMember(id,owner,member).andExpect(status().isCreated());addMember(id,owner,member).andExpect(status().isConflict());mvc.perform(post("/api/v1/companies/{id}/members",id).headers(identity(owner,"EMPLOYER")).contentType(MediaType.APPLICATION_JSON).content("{\"userId\":\""+UUID.randomUUID()+"\",\"role\":\"OWNER\"}")).andExpect(status().isForbidden());}
 @Test void publicCompanyResponseHasNoMembersOrObjectKeys()throws Exception{String id=createCompany(UUID.randomUUID());mvc.perform(get("/api/v1/companies/{id}",id)).andExpect(status().isOk()).andExpect(jsonPath("$.data.members").doesNotExist()).andExpect(jsonPath("$.data.logoObjectKey").doesNotExist());}
 @Test void validPdfUploadsListsAndUsesSafeKey()throws Exception{UUID u=UUID.randomUUID();String body=mvc.perform(multipart("/api/v1/candidates/me/cvs").file(new org.springframework.mock.web.MockMultipartFile("file","../cv.pdf","application/pdf","%PDF-valid".getBytes())).headers(identity(u,"CANDIDATE"))).andExpect(status().isCreated()).andExpect(jsonPath("$.data.objectKey").doesNotExist()).andReturn().getResponse().getContentAsString();assertThat(body).doesNotContain("cvs/");assertThat(storage.objects.keySet()).allMatch(k->k.matches("cvs/[0-9a-f-]{36}/[0-9a-f-]{36}\\.pdf"));mvc.perform(get("/api/v1/candidates/me/cvs").headers(identity(u,"CANDIDATE"))).andExpect(jsonPath("$.data.length()").value(1));}
 @Test void invalidExtensionMimeSignatureAndOversizeAreRejected()throws Exception{UUID u=UUID.randomUUID();mvc.perform(multipart("/api/v1/candidates/me/cvs").file(new org.springframework.mock.web.MockMultipartFile("file","cv.txt","application/pdf","%PDF-x".getBytes())).headers(identity(u,"CANDIDATE"))).andExpect(status().isUnsupportedMediaType());mvc.perform(multipart("/api/v1/candidates/me/cvs").file(new org.springframework.mock.web.MockMultipartFile("file","cv.pdf","text/plain","%PDF-x".getBytes())).headers(identity(u,"CANDIDATE"))).andExpect(status().isUnsupportedMediaType());mvc.perform(multipart("/api/v1/candidates/me/cvs").file(new org.springframework.mock.web.MockMultipartFile("file","cv.pdf","application/pdf","not-a-pdf".getBytes())).headers(identity(u,"CANDIDATE"))).andExpect(status().isUnsupportedMediaType());mvc.perform(multipart("/api/v1/candidates/me/cvs").file(new org.springframework.mock.web.MockMultipartFile("file","cv.pdf","application/pdf",("%PDF-"+"x".repeat(40)).getBytes())).headers(identity(u,"CANDIDATE"))).andExpect(status().isPayloadTooLarge());}
 @Test void candidateCannotDeleteAnotherCandidatesCv()throws Exception{UUID a=UUID.randomUUID();String id=upload(a);mvc.perform(delete("/api/v1/candidates/me/cvs/{id}",id).headers(identity(UUID.randomUUID(),"CANDIDATE"))).andExpect(status().isNotFound());assertThat(storage.objects).isNotEmpty();}
 @Test void deleteRemovesMetadataAndObject()throws Exception{UUID u=UUID.randomUUID();String id=upload(u);mvc.perform(delete("/api/v1/candidates/me/cvs/{id}",id).headers(identity(u,"CANDIDATE"))).andExpect(status().isNoContent());assertThat(storage.objects).isEmpty();}
 @Test void internalContractsAreProtectedAndCorrect()throws Exception{UUID candidate=UUID.randomUUID();String cv=upload(candidate);mvc.perform(get("/internal/cvs/{id}/validation",cv).param("candidateId",candidate.toString())).andExpect(status().isUnauthorized());mvc.perform(get("/internal/cvs/{id}/validation",cv).param("candidateId",candidate.toString()).header("X-Internal-Token","test-internal-secret")).andExpect(status().isOk()).andExpect(jsonPath("$.data.valid").value(true)).andExpect(jsonPath("$.data.objectKey").isNotEmpty());mvc.perform(get("/internal/cvs/{id}/validation",cv).param("candidateId",UUID.randomUUID().toString()).header("X-Internal-Token","test-internal-secret")).andExpect(status().isNotFound());UUID owner=UUID.randomUUID();String company=createCompany(owner);mvc.perform(get("/internal/companies/{id}/authorization",company).param("userId",owner.toString()).header("X-Internal-Token","test-internal-secret")).andExpect(jsonPath("$.data.memberRole").value("OWNER"));mvc.perform(get("/internal/companies/{id}/authorization",company).param("userId",UUID.randomUUID().toString()).header("X-Internal-Token","test-internal-secret")).andExpect(jsonPath("$.data.canManage").value(false));}
 private String createCompany(UUID owner)throws Exception{return tools.jackson.databind.json.JsonMapper.builder().build().readTree(mvc.perform(post("/api/v1/companies").headers(identity(owner,"EMPLOYER")).contentType(MediaType.APPLICATION_JSON).content(companyJson("Acme"))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString()).get("data").get("id").asText();}
 private org.springframework.test.web.servlet.ResultActions addMember(String c,UUID o,UUID m)throws Exception{return mvc.perform(post("/api/v1/companies/{id}/members",c).headers(identity(o,"EMPLOYER")).contentType(MediaType.APPLICATION_JSON).content("{\"userId\":\""+m+"\",\"role\":\"RECRUITER\"}"));}
 private String upload(UUID u)throws Exception{return tools.jackson.databind.json.JsonMapper.builder().build().readTree(mvc.perform(multipart("/api/v1/candidates/me/cvs").file(new org.springframework.mock.web.MockMultipartFile("file","cv.pdf","application/pdf","%PDF-ok".getBytes())).headers(identity(u,"CANDIDATE"))).andReturn().getResponse().getContentAsString()).get("data").get("id").asText();}
 private org.springframework.http.HttpHeaders identity(UUID u,String role){var h=new org.springframework.http.HttpHeaders();h.set("X-User-Id",u.toString());h.set("X-User-Role",role);return h;} private String companyJson(String n){return "{\"name\":\""+n+"\",\"description\":\"Public\",\"address\":\"Hanoi\"}";}
 @TestConfiguration static class StorageConfig {@Bean @Primary MemoryStorage storage(){return new MemoryStorage();}}
 static class MemoryStorage implements ObjectStorage {final Map<String,byte[]> objects=new ConcurrentHashMap<>();public void put(String k,InputStream d,long s,String t){try{objects.put(k,d.readAllBytes());}catch(IOException e){throw new RuntimeException(e);}}public void delete(String k){objects.remove(k);}}
}
