package com.example.notification_service;
import com.example.notification_service.entity.NotificationStatus;import com.example.notification_service.repository.*;import org.junit.jupiter.api.*;import org.springframework.amqp.core.*;import org.springframework.amqp.rabbit.core.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.mail.javamail.JavaMailSender;import org.springframework.test.context.*;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.testcontainers.containers.*;import org.testcontainers.junit.jupiter.*;import tools.jackson.databind.json.JsonMapper;import java.time.*;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;

@Testcontainers @SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.NONE,properties="management.health.mail.enabled=false") @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class NotificationServiceApplicationTests{@org.testcontainers.junit.jupiter.Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:17-alpine");@org.testcontainers.junit.jupiter.Container static final RabbitMQContainer RABBIT=new RabbitMQContainer("rabbitmq:4-management-alpine");static final String EXCHANGE="test.recruitment.events",QUEUE="test.notifications",DLX="test.notifications.dlx",DLQ="test.notifications.dlq";@Autowired RabbitTemplate rabbit;@Autowired RabbitAdmin admin;@Autowired NotificationRepository notifications;@Autowired ProcessedEventRepository processed;@Autowired JdbcTemplate jdbc;@Autowired JsonMapper json;@MockitoBean JavaMailSender mail;
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",POSTGRES::getJdbcUrl);r.add("spring.datasource.username",POSTGRES::getUsername);r.add("spring.datasource.password",POSTGRES::getPassword);r.add("spring.rabbitmq.host",RABBIT::getHost);r.add("spring.rabbitmq.port",RABBIT::getAmqpPort);r.add("spring.rabbitmq.username",RABBIT::getAdminUsername);r.add("spring.rabbitmq.password",RABBIT::getAdminPassword);r.add("notification.messaging.exchange",()->EXCHANGE);r.add("notification.messaging.queue",()->QUEUE);r.add("notification.messaging.dlx",()->DLX);r.add("notification.messaging.dlq",()->DLQ);r.add("notification.messaging.retry-attempts",()->"3");}
 @BeforeEach void clean(){admin.purgeQueue(QUEUE,true);admin.purgeQueue(DLQ,true);processed.deleteAll();notifications.deleteAll();reset(mail);}
 @Test @Order(1) void flywayAndHibernateValidatePostgresAndTopology(){Integer n=jdbc.queryForObject("select count(*) from information_schema.tables where table_schema='public' and table_name in ('notifications','processed_events')",Integer.class);assertThat(n).isEqualTo(2);assertThat(admin.getQueueProperties(QUEUE)).isNotNull();assertThat(admin.getQueueProperties(DLQ)).isNotNull();}
 @Test @Order(2) void consumesSubmittedAndSuppressesDuplicate()throws Exception{UUID event=UUID.randomUUID();send(event,"APPLICATION_SUBMITTED",1,"candidate@example.com",null,"APPLIED");await(()->processed.existsById(event));send(event,"APPLICATION_SUBMITTED",1,"candidate@example.com",null,"APPLIED");await(()->messageCount(QUEUE)==0);assertThat(notifications.findByEventId(event)).get().extracting("status").isEqualTo(NotificationStatus.SENT);verify(mail,times(1)).send(any(org.springframework.mail.SimpleMailMessage.class));}
 @Test @Order(3) void consumesStatusChangedWithCorrectTemplate()throws Exception{UUID event=UUID.randomUUID();send(event,"APPLICATION_STATUS_CHANGED",1,"candidate@example.com","APPLIED","SCREENING");await(()->processed.existsById(event));assertThat(notifications.findByEventId(event)).get().extracting("templateCode").isEqualTo("APPLICATION_STATUS_CHANGED");verify(mail).send(argThat((org.springframework.mail.SimpleMailMessage m)->m.getText().contains("APPLIED")&&m.getText().contains("SCREENING")));}
 @Test @Order(4) void transientMailFailureRetriesThenSucceeds()throws Exception{AtomicInteger attempts=new AtomicInteger();doAnswer(i->{if(attempts.incrementAndGet()<3)throw new org.springframework.mail.MailSendException("temporary");return null;}).when(mail).send(any(org.springframework.mail.SimpleMailMessage.class));UUID event=UUID.randomUUID();send(event,"APPLICATION_SUBMITTED",1,"candidate@example.com",null,"APPLIED");await(()->processed.existsById(event));assertThat(attempts).hasValue(3);assertThat(notifications.count()).isEqualTo(1);}
 @Test @Order(5) void invalidVersionAndRecipientGoToDlq()throws Exception{send(UUID.randomUUID(),"APPLICATION_SUBMITTED",99,"candidate@example.com",null,"APPLIED");await(()->messageCount(DLQ)>=1);send(UUID.randomUUID(),"APPLICATION_SUBMITTED",1,"not-an-email",null,"APPLIED");await(()->messageCount(DLQ)>=2);assertThat(processed.count()).isZero();verifyNoInteractions(mail);}
 private void send(UUID event,String type,int version,String email,String oldStatus,String next)throws Exception{UUID app=UUID.randomUUID();String body="{\"eventId\":\""+event+"\",\"eventType\":\""+type+"\",\"eventVersion\":"+version+",\"occurredAt\":\""+Instant.now()+"\",\"producer\":\"application-service\",\"data\":{\"applicationId\":\""+app+"\",\"jobId\":\""+UUID.randomUUID()+"\",\"companyId\":\""+UUID.randomUUID()+"\",\"candidateId\":\""+UUID.randomUUID()+"\",\"candidateEmail\":\""+email+"\",\"jobTitle\":\"Engineer\",\"oldStatus\":"+(oldStatus==null?"null":"\""+oldStatus+"\"")+",\"newStatus\":\""+next+"\",\"correlationId\":\"trace-123\"}}";MessageProperties p=new MessageProperties();p.setContentType(MessageProperties.CONTENT_TYPE_JSON);p.setDeliveryMode(MessageDeliveryMode.PERSISTENT);rabbit.send(EXCHANGE,type.equals("APPLICATION_SUBMITTED")?"application.submitted":"application.status-changed",new Message(body.getBytes(java.nio.charset.StandardCharsets.UTF_8),p));}
 private long messageCount(String q){Object n=admin.getQueueProperties(q).get(RabbitAdmin.QUEUE_MESSAGE_COUNT);return ((Number)n).longValue();}private void await(java.util.function.BooleanSupplier condition)throws Exception{long end=System.nanoTime()+Duration.ofSeconds(12).toNanos();while(System.nanoTime()<end){if(condition.getAsBoolean())return;Thread.sleep(50);}throw new AssertionError("Asynchronous condition timed out");}}
